### ISSUE TITLE
Support for async payment processing

### ISSUE THREAD

**Issue by j-mok** [VirtoCommerce/vc-module-payment#55]
Is there a way to asynchronously process payment state transitions? From what I understand, currently `PaymentMethod` only offer classic, blocking hooks:

https://github.com/VirtoCommerce/vc-module-payment/blob/52effa3fa9b6603e1d1b4a422f10b064e40d6f42/src/VirtoCommerce.Payment.Core/Model/PaymentMethod.cs#L93-L125

We're aiming for a completely asynchronous processing model in our product's modules. Our custom payment methods, that are still blocking, are a major thorn in our side. I think that async (Task-based) processing in payment methods is particularly justified as:
- payment state transitions usually involve network calls,
- a busy e-commerce app can generate significant traffic in this area,
- frequent blocking calls will freeze thread pool threads and degrade overall platform performance.

Now I understand that these methods get called elsewhere (Orders module? Correct me if I'm wrong) and this module serves as a contract to build custom payment methods on, so introducing async hooks would span more than one module, but I think it's still worth a shot. If carefully implemented, it could be backward-compatible and existing synchronous payment methods would work as before.

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-8428 has been created

**Comment by OlegoO** [comment]
Thank you for reaching out to us with your feature request. We greatly appreciate your engagement and enthusiasm for enhancing the Virto Commerce Platform.

After careful consideration, we regret to inform you that, at this time, we do not have plans to implement the requested feature in the year 2024. However, please be assured that your suggestion has been diligently recorded in our backlog. Feature requests like yours play a crucial role in shaping the evolution of our platform.

While we may not be able to accommodate this specific request immediately, the priority of features can change based on various factors, including the accumulation of similar requests or the introduction of new functionalities. Your valuable input remains on our radar, and we encourage you to continue sharing your thoughts and ideas with us.

We truly appreciate your understanding and your commitment to making Virto Commerce even better. If you have any further questions or if there's anything else we can assist you with, please feel free to let us know.

Virto Commerce is an open-source project, and we welcome contributions from our community members. If you are interested and have the capability to implement this feature, we encourage you to consider contributing to the Virto Commerce GitHub repository.
